//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacen_Motos.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class repuestos_motosEntities : DbContext
    {
        public repuestos_motosEntities()
            : base("name=repuestos_motosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        [JsonIgnore]
        public virtual DbSet<garantia> garantia { get; set; }
        [JsonIgnore]
        public virtual DbSet<proveedor> proveedor { get; set; }
        [JsonIgnore]
        public virtual DbSet<respuestos> respuestos { get; set; }
        [JsonIgnore]
        public virtual DbSet<servicio_mecanica> servicio_mecanica { get; set; }
        [JsonIgnore]
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
