//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacen_Motos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class respuestos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public respuestos()
        {
            this.servicio_mecanica = new HashSet<servicio_mecanica>();
        }
    
        public int Codigo { get; set; }
        public string Nombre_repuesto { get; set; }
        public string categoria_repuesto { get; set; }
        public string marca { get; set; }
        public Nullable<int> cantidad_respuesto { get; set; }
        public Nullable<double> precios_respuesto { get; set; }
        public Nullable<int> ID_proveedor { get; set; }
        public Nullable<int> C_Garantia { get; set; }
    
        public virtual garantia garantia { get; set; }
        public virtual proveedor proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servicio_mecanica> servicio_mecanica { get; set; }
    }
}
